# Generated by Django 3.0.7 on 2021-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210731_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='team',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
