# Generated by Django 3.0.7 on 2021-08-01 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210731_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
