# Generated by Django 3.0.7 on 2021-08-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210801_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
    ]
